In [ ]:
import torch

In [ ]:
# we may create tensors from ptyhon lists
A = [[6, 9, 2],
     [3, 3, 7],
     [1, 0, 3]]

A_tensor = torch.tensor(A)

print(A_tensor)

tensor([[6, 9, 2],
        [3, 3, 7],
        [1, 0, 3]])


In [ ]:
# or numpy arrays
import numpy as np

B = np.array([0,1,2,3])
B_tensor = torch.tensor(B)

print(B_tensor)

tensor([0, 1, 2, 3])


In [ ]:
# or directly using using the torch.tensor constuctor
C_tensor = torch.tensor([[1., -1.], [1., -1.]])

print(C_tensor)

tensor([[ 1., -1.],
        [ 1., -1.]])


In [ ]:
# attributes of a tensor:

# .dtype
print(A_tensor.dtype)  # to know the datatype stored in your tensor

# .shape
print(A_tensor.shape)  # to know the shape of the tensor i.e. the dimensions

# .device
print(A_tensor.device) # to know what device the tensor is being computed

torch.int64
torch.Size([3, 3])
cpu


In [ ]:
# some useful ways to generate tensors

zero_tensor = torch.zeros((4,2), requires_grad = True)  # generates a tensor of zeroes
print(zero_tensor)

one_tensor = torch.ones(4,2) # generates a tensor of ones
print(one_tensor)

random_tensor = torch.rand(4,2,2) # generates random numbers between 0 and 1
print(random_tensor)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[[0.9249, 0.0019],
         [0.1694, 0.7866]],

        [[0.3451, 0.1279],
         [0.9052, 0.3376]],

        [[0.5508, 0.3298],
         [0.7562, 0.3996]],

        [[0.3012, 0.8795],
         [0.9684, 0.3680]]])


In [ ]:
reshaped_tensor = random_tensor.reshape(4,-1) # reshapes the data without losing any of it

print(reshaped_tensor.shape)
print(reshaped_tensor)

torch.Size([4, 4])
tensor([[0.9249, 0.0019, 0.1694, 0.7866],
        [0.3451, 0.1279, 0.9052, 0.3376],
        [0.5508, 0.3298, 0.7562, 0.3996],
        [0.3012, 0.8795, 0.9684, 0.3680]])


In [ ]:
problematic_reshaped_tensor = random_tensor.reshape(4,3) # this reshaping is not allowed

RuntimeError: ignored