In [ ]:
import numpy as np
import cv2  # Image reading library

In [ ]:
def Convolution(image, kernel):
    # Image and kernel should be numpy matrices. Kernel should be 3 x 3

    _image = np.copy(image)/255 # Normalization
    ry, rx = tuple(image.shape)
    new_image = np.empty_like(_image)
    _image = np.concatenate([np.zeros(rx).reshape((1,-1)), _image, np.zeros(rx).reshape((1,-1))])
    _image = np.concatenate([np.zeros(ry+2).reshape([-1,1]), _image, np.zeros(ry+2).reshape([-1,1])], axis=1)
    for row in range(1,ry+1):
        for col in range(1,rx+1):
            section = _image[row-1:row+2, col-1:col+2]
            try: new_image[row-1][col-1] = np.sum(section*kernel)
            except: print(row, col)
    return (new_image)*255

sobel_v = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
sobel_h = sobel_v.T
print(sobel_h)
gaussian_blur = np.array([[0.075, 0.124, 0.075], [.124, .204, .124], [.075, .124, .075]])

[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]


In [ ]:
img = cv2.imread('football.png', cv2.IMREAD_GRAYSCALE)
print((img.shape))
img_edges_v = Convolution(img, sobel_v)
cv2.imwrite("Edges_vertical.png", img_edges_v)
img_edges_h = Convolution(img, sobel_h)
cv2.imwrite('Edges_horizontal.png', img_edges_h)
cv2.imwrite('Edges.png', (img_edges_v**2+img_edges_h**2)**0.5)
img_blur = Convolution(img, gaussian_blur)
cv2.imwrite('Gaussian Blur.png', img_blur)
img_gauss_edges_v = Convolution(img_blur, sobel_v)
img_gauss_edges_h = Convolution(img_blur, sobel_h)
cv2.imwrite('Gaussian Blur + Edges.png', (img_gauss_edges_v**2+img_gauss_edges_h**2)**0.5)

(154, 222)


True

In [ ]:
ppt_conv = np.array(
    [[50, 165, 67, 0],
    [94, 23, 88, 12],
    [178, 56, 90, 64],
    [234, 208, 78, 123]]
)
print(Convolution(ppt_conv, sobel_v))
ppt_conv2 = np.array(
    [[3,3,2,1,0],
    [0,0,1,3,1],
    [3,1,2,2,3],
    [2,0,0,2,2],
    [2,0,0,0,1]]
)
kernel_ppt = np.array([
    [0,1,2],
    [2,2,0],
    [0,1,2]
])
print(Convolution(ppt_conv2, kernel_ppt))

[[-353.  -28.  341.  222.]
 [-267.   83.  179.  333.]
 [-343.  338.   80.  346.]
 [-472.  400.  162.  246.]]
[[ 6. 14. 17. 11.  3.]
 [14. 12. 12. 17. 11.]
 [ 8. 10. 17. 19. 13.]
 [11.  9.  6. 14. 12.]
 [ 6.  4.  4.  6.  4.]]
